### PR TITLE
Removes cap on `mdit-py-plugins` dependency

### PR DESCRIPTION
**Pull request by kdeldycke**
Closes:
- https://github.com/hukkin/mdformat-gfm/issues/27

Addresses:
- https://github.com/KyleKing/mdformat-admon/issues/15

### CODE REVIEW

**Comment by hukkin** [comment]
Thanks!

**Comment by kdeldycke** [comment]
Thanks @hukkin for the merge! Any plan for a new release of `mdformat-gfm`?

**Comment by hukkin** [comment]
I'll make a release when the failing test is fixed. Can't promise when. At a quick glance it seems to me like it's a result of an updated `markdown-it-py` or maybe `linkify-it-py` . If `markdown-it-py`, it would be interesting to know how Javascript `markdown-it` works here and whether the change is a bug or intended new behavior.

**Comment by KyleKing** [comment]
FWIW, #30 should resolve the CI failures and works on my fork: https://github.com/KyleKing/mdformat-gfm/actions/runs/7477630457. I added a few notes on what is happening there

**Pull request merged**
